#include "Primitives.h"

#include <cmath>
#include <vector>
#include <glm/glm.hpp>

// Use a local constant instead of M_PI — avoids MSVC's _USE_MATH_DEFINES
// dependency and is guaranteed to be available everywhere.
static constexpr float PI = 3.14159265358979323846f;

// ============================================================
// createCube — Unit cube with flat normals.
//
// We need 24 vertices (4 per face × 6 faces) rather than 8
// because each face needs its own normal direction.
// Using shared corner vertices would produce averaged normals
// that look wrong for a hard-edged shape like a cube.
// ============================================================
Mesh Primitives::createCube(float s) {
    float h = s * 0.5f; // half-size

    std::vector<Vertex>       vertices;
    std::vector<unsigned int> indices;
    vertices.reserve(24);
    indices.reserve(36);

    // Helper lambda: push one quad (4 verts, 2 triangles) onto the buffers.
    // pos0..pos3 = CCW corners when viewed from outside.
    // norm       = outward-facing face normal.
    auto addFace = [&](
        glm::vec3 p0, glm::vec3 p1, glm::vec3 p2, glm::vec3 p3,
        glm::vec3 norm)
    {
        unsigned int base = static_cast<unsigned int>(vertices.size());

        // Standard UV corners: (0,0) (1,0) (1,1) (0,1)
        glm::vec2 uvs[4] = {{0.f,0.f},{1.f,0.f},{1.f,1.f},{0.f,1.f}};
        glm::vec3 pts[4] = { p0, p1, p2, p3 };

        for (int i = 0; i < 4; ++i) {
            Vertex v;
            v.position  = pts[i];
            v.normal    = norm;
            v.texCoords = uvs[i];
            vertices.push_back(v);
        }

        // Two CCW triangles: 0-1-2 and 0-2-3
        indices.insert(indices.end(), {
            base+0, base+1, base+2,
            base+0, base+2, base+3
        });
    };

    // 6 faces — corners listed CCW when viewed from outside the cube
    addFace({-h,-h, h}, { h,-h, h}, { h, h, h}, {-h, h, h}, { 0, 0, 1}); // Front  (+Z)
    addFace({ h,-h,-h}, {-h,-h,-h}, {-h, h,-h}, { h, h,-h}, { 0, 0,-1}); // Back   (-Z)
    addFace({-h,-h,-h}, {-h,-h, h}, {-h, h, h}, {-h, h,-h}, {-1, 0, 0}); // Left   (-X)
    addFace({ h,-h, h}, { h,-h,-h}, { h, h,-h}, { h, h, h}, { 1, 0, 0}); // Right  (+X)
    addFace({-h, h, h}, { h, h, h}, { h, h,-h}, {-h, h,-h}, { 0, 1, 0}); // Top    (+Y)
    addFace({-h,-h,-h}, { h,-h,-h}, { h,-h, h}, {-h,-h, h}, { 0,-1, 0}); // Bottom (-Y)

    return Mesh(vertices, indices);
}

// ============================================================
// createSphere — UV sphere via longitude/latitude parameterisation.
//
// Vertices are generated by sweeping a half-circle (stack angle)
// around the Y axis (sector angle).
//
//   stack angle  phi   ∈ [+π/2, -π/2]   top → bottom
//   sector angle theta ∈ [0,     2π]     around Y
//
//   x = r * cos(phi) * cos(theta)
//   y = r * sin(phi)
//   z = r * cos(phi) * sin(theta)
//
// Normals = vertex / r  (analytically exact for a perfect sphere).
// ============================================================
Mesh Primitives::createSphere(float radius, int sectors, int stacks) {
    if (sectors < 3) sectors = 3;
    if (stacks  < 2) stacks  = 2;

    std::vector<Vertex>       vertices;
    std::vector<unsigned int> indices;

    const float sectorStep = 2.f * PI / static_cast<float>(sectors);
    const float stackStep  =       PI / static_cast<float>(stacks);

    // Generate (stacks+1) × (sectors+1) vertices
    for (int i = 0; i <= stacks; ++i) {
        // phi sweeps from +π/2 (north pole) down to -π/2 (south pole)
        float phi = PI / 2.f - static_cast<float>(i) * stackStep;
        float xz  = radius * std::cos(phi); // radius of the current latitude circle
        float y   = radius * std::sin(phi);

        for (int j = 0; j <= sectors; ++j) {
            float theta = static_cast<float>(j) * sectorStep;

            Vertex v;
            v.position.x  = xz * std::cos(theta);
            v.position.y  = y;
            v.position.z  = xz * std::sin(theta);

            // For a unit sphere the normal equals the normalised position.
            // glm::normalize handles the radius scaling automatically.
            v.normal      = glm::normalize(v.position);

            v.texCoords.x = static_cast<float>(j) / static_cast<float>(sectors);
            v.texCoords.y = static_cast<float>(i) / static_cast<float>(stacks);

            vertices.push_back(v);
        }
    }

    // Generate indices — each quad is two triangles
    for (int i = 0; i < stacks; ++i) {
        int k1 = i * (sectors + 1);      // top-left of quad
        int k2 = k1 + sectors + 1;       // bottom-left of quad

        for (int j = 0; j < sectors; ++j, ++k1, ++k2) {
            // Upper triangle (skip degenerate triangle at north pole)
            if (i != 0) {
                indices.push_back(static_cast<unsigned int>(k1));
                indices.push_back(static_cast<unsigned int>(k2));
                indices.push_back(static_cast<unsigned int>(k1 + 1));
            }
            // Lower triangle (skip degenerate triangle at south pole)
            if (i != stacks - 1) {
                indices.push_back(static_cast<unsigned int>(k1 + 1));
                indices.push_back(static_cast<unsigned int>(k2));
                indices.push_back(static_cast<unsigned int>(k2 + 1));
            }
        }
    }

    return Mesh(vertices, indices);
}

// ============================================================
// createPlane — A flat quad in the XZ plane, normals pointing +Y.
// ============================================================
Mesh Primitives::createPlane(float s) {
    std::vector<Vertex> vertices;
    vertices.reserve(4);

    // Push each vertex explicitly — avoids aggregate-init issues on MSVC
    auto v = [](float x, float z, float u, float w) -> Vertex {
        Vertex vtx;
        vtx.position  = {x, 0.f, z};
        vtx.normal    = {0.f, 1.f, 0.f};
        vtx.texCoords = {u, w};
        return vtx;
    };

    vertices.push_back(v(-s, -s, 0.f, 0.f));
    vertices.push_back(v( s, -s, 1.f, 0.f));
    vertices.push_back(v( s,  s, 1.f, 1.f));
    vertices.push_back(v(-s,  s, 0.f, 1.f));

    std::vector<unsigned int> indices = { 0, 1, 2,  0, 2, 3 };

    return Mesh(vertices, indices);
}
